# Generated by Django 4.0.7 on 2022-11-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0002_alter_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, default='onebyone.png', null=True, upload_to='images/', verbose_name='image'),
        ),
    ]
