# Generated by Django 4.0.7 on 2022-11-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0003_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
