# Generated by Django 4.1.2 on 2022-11-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_karma'),
        ('accounts', '0002_user_profile_picture'),
    ]

    operations = [
    ]
