# Generated by Django 4.0.7 on 2022-11-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20221107_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_pfp.jpg', null=True, upload_to='images/'),
        ),
    ]
