# Generated by Django 4.1.2 on 2022-10-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_karma',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
