# Generated by Django 4.0.7 on 2022-10-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='karma_score',
            field=models.IntegerField(default=0),
        ),
    ]
