# Generated by Django 4.1.2 on 2022-11-03 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0002_alter_post_post_karma'),
    ]

    operations = [
        migrations.CreateModel(
            name='upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posty.post')),
            ],
        ),
        migrations.CreateModel(
            name='downvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posty.post')),
            ],
        ),
    ]
