# Generated by Django 4.0.7 on 2022-10-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0002_post_karma_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='karma_score',
            field=models.IntegerField(default=0),
        ),
    ]
