# Generated by Django 4.0.7 on 2022-10-31 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0003_profile_karma_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='karma_score',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='karma_score',
        ),
    ]
