# Generated by Django 4.1.2 on 2022-11-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0004_remove_post_karma_score_remove_profile_karma_score'),
        ('posty', '0006_remove_profile_user_karma'),
    ]

    operations = [
    ]
