# Generated by Django 4.1.2 on 2022-11-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0009_alter_post_body_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_karma',
        ),
    ]
