# Generated by Django 4.1.2 on 2022-11-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0010_rename_body_comment_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='body',
        ),
    ]
