# Generated by Django 4.1.2 on 2022-11-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0011_rename_comment_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commentCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
