# Generated by Django 4.1.2 on 2022-11-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0012_post_commentcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=500),
        ),
    ]
