# Generated by Django 4.1.2 on 2022-11-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0013_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=350),
        ),
    ]
