# Generated by Django 4.0.7 on 2022-11-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0017_alter_post_body_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
