# Generated by Django 4.0.7 on 2022-11-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0019_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=255),
        ),
    ]
