# Generated by Django 4.0.7 on 2022-11-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0021_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=255),
        ),
    ]
