# Generated by Django 4.0.7 on 2022-11-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0022_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='editied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='editiedOn',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
