# Generated by Django 4.0.7 on 2022-11-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0024_rename_editiedon_comment_editied_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='editied_on',
        ),
    ]
