# Generated by Django 4.0.7 on 2022-12-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0025_remove_comment_editied_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='editied',
            new_name='edited',
        ),
    ]
