# Generated by Django 4.0.7 on 2022-12-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0026_rename_editied_comment_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
